### ISSUE TITLE
这个是i56300,960m那一款的吗?

### ISSUE THREAD

**Issue by imamiao** [Measureless/Hackintosh_Hasee_Z6-SL5D1#1]

**Comment by KalonPeng** [comment]
是的

**Comment by imamiao** [comment]
嗯,感谢呀

**Comment by imamiao** [comment]
麻烦还要再请教你.😂
这套EFI 装Mojave和Catalina都可以么?

**Comment by KalonPeng** [comment]
> 麻烦还要再请教你.😂
> 这套EFI 装Mojave和Catalina都可以么?

正常来说是可以的，我后面搞了新的EFI，目前用着从14.6直升到15.3都没有问题，99%完成度，十分接近白果了，双系统爽歪歪！

不过我的是SL7D1，CPU跟SL5D1有差别，我的是6700HQ，但方法都一样（可能选择的机型不同），应该也是通用的。

**Comment by imamiao** [comment]
折腾了半天能进入系统了,但是感觉是没有想象中那么流畅,不管是视觉上还是应用打开速度上.
电脑是有NVME固态的,但还是感觉卡卡的...你装上用起来是比较流畅的么?

**Comment by KalonPeng** [comment]
> 折腾了半天能进入系统了,但是感觉是没有想象中那么流畅,不管是视觉上还是应用打开速度上.
> 电脑是有NVME固态的,但还是感觉卡卡的...你装上用起来是比较流畅的么?

你的是显卡没驱动成功，我的很流畅，你参考一下教程，注入一下显卡驱动就可以了

**Comment by imamiao** [comment]
大哥能加个好友吗? 现在我搞得都不知道是不是驱动成功了😂
我的qq:1225347740,或者我加你

**Comment by KalonPeng** [comment]
> 大哥能加个好友吗? 现在我搞得都不知道是不是驱动成功了😂
> 我的qq:1225347740,或者我加你

好，我加你（一般看系统信息就知道了，显存显示Intel HD Graphics 530 1536 MB，就是可以了的

**Comment by imamiao** [comment]
我用你的EFI开机的时候,会卡进度条.偶尔一次进去系统之后也很卡. 显卡是识别的Intel HD Graphics 530 1536 MB,但还是一样卡的.
别人的z6都很顺利,我的这么难,都好像不是一台机子一样.😢 我之前给一台台式机装的时候也没有这么难啊😭
大哥能不能加个好友帮我看一下,请你喝咖啡.

**Comment by KalonPeng** [comment]
> 我用你的EFI开机的时候,会卡进度条.偶尔一次进去系统之后也很卡. 显卡是识别的Intel HD Graphics 530 1536 MB,但还是一样卡的.
> 别人的z6都很顺利,我的这么难,都好像不是一台机子一样.😢 我之前给一台台式机装的时候也没有这么难啊😭
> 大哥能不能加个好友帮我看一下,请你喝咖啡.

擦，前两天忘了，已经发好友申请了

**Comment by KalonPeng** [comment]
> 我用你的EFI开机的时候,会卡进度条.偶尔一次进去系统之后也很卡. 显卡是识别的Intel HD Graphics 530 1536 MB,但还是一样卡的.
> 别人的z6都很顺利,我的这么难,都好像不是一台机子一样.😢 我之前给一台台式机装的时候也没有这么难啊😭
> 大哥能不能加个好友帮我看一下,请你喝咖啡.

你是漏了一个补丁，装上就好了

**Comment by imamiao** [comment]
谢谢老哥，老哥人很好😊

**Comment by qianmoeast** [comment]
oc可以上车吗

**Comment by KalonPeng** [comment]
> oc可以上车吗

没有试，求稳不追新，等稳定在搞，你可以试试

**Comment by qianmoeast** [comment]
[已经尝试了很长时间实在是没办法了]

**Comment by qianmoeast** [comment]
不知是否可以邮箱讨论学习一下

**Comment by KalonPeng** [comment]
> 不知是否可以邮箱讨论学习一下

我短期都不会再折腾了（clover用着挺好），你可以看看远景上的大佬有没有更新

**Comment by imamiao** [comment]
我最近又发现一个问题，我前两天买了个一4k显示器创维的28U1，我用HDMI去连，电脑内置显示屏会闪黑几下，然后显示器就显示无信号进休眠模式了。内置显示屏在闪黑的时候能看到电脑上能识别出来这台显示器，就是显示器没有画面。用别的4K显示器就能正常显示（虽然只能到30fps）。
虽然感觉跟电脑没关系，但还是有点疑惑。。。辣鸡创维哈哈哈哈哈哈

**Comment by KalonPeng** [comment]
> 我最近又发现一个问题，我前两天买了个一4k显示器创维的28U1，我用HDMI去连，电脑内置显示屏会闪黑几下，然后显示器就显示无信号进休眠模式了。内置显示屏在闪黑的时候能看到电脑上能识别出来这台显示器，就是显示器没有画面。用别的4K显示器就能正常显示（虽然只能到30fps）。
> 虽然感觉跟电脑没关系，但还是有点疑惑。。。辣鸡创维哈哈哈哈哈哈

更新一下whatevergreen看看，黑果是有点迷，全看运气

**Comment by WangYuan611** [comment]
> > 麻烦还要再请教你.😂
> > 这套EFI 装Mojave和Catalina都可以么?
> 
> 正常来说是可以的，我后面搞了新的EFI，目前用着从14.6直升到15.3都没有问题，99%完成度，十分接近白果了，双系统爽歪歪！
> 
> 不过我的是SL7D1，CPU跟SL5D1有差别，我的是6700HQ，但方法都一样（可能选择的机型不同），应该也是通用的。

您好，我的也是神舟Z6-SL7D1，目前电池显示不出来，HDMI无法外接屏幕。我装的是黑果小兵的10.15.4，能麻烦您把EFI文件发我一份儿吗？万分感谢。

**Comment by KalonPeng** [comment]
> > > 麻烦还要再请教你.😂
> > > 这套EFI 装Mojave和Catalina都可以么?
> > 
> > 
> > 正常来说是可以的，我后面搞了新的EFI，目前用着从14.6直升到15.3都没有问题，99%完成度，十分接近白果了，双系统爽歪歪！
> > 不过我的是SL7D1，CPU跟SL5D1有差别，我的是6700HQ，但方法都一样（可能选择的机型不同），应该也是通用的。
> 
> 您好，我的也是神舟Z6-SL7D1，目前电池显示不出来，HDMI无法外接屏幕。我装的是黑果小兵的10.15.4，能麻烦您把EFI文件发我一份儿吗？万分感谢。

我单独搞一个git，上传到那你可以去看看

**Comment by WangYuan611** [comment]
> > > > 麻烦还要再请教你.😂
> > > > 这套EFI 装Mojave和Catalina都可以么?
> > > 
> > > 
> > > 正常来说是可以的，我后面搞了新的EFI，目前用着从14.6直升到15.3都没有问题，99%完成度，十分接近白果了，双系统爽歪歪！
> > > 不过我的是SL7D1，CPU跟SL5D1有差别，我的是6700HQ，但方法都一样（可能选择的机型不同），应该也是通用的。
> > 
> > 
> > 您好，我的也是神舟Z6-SL7D1，目前电池显示不出来，HDMI无法外接屏幕。我装的是黑果小兵的10.15.4，能麻烦您把EFI文件发我一份儿吗？万分感谢。
> 
> 我单独搞一个git，上传到那你可以去看看

好的，谢谢~

**Comment by Utopin** [comment]
> > > > 麻烦还要再请教你.😂
> > > > 这套EFI 装Mojave和Catalina都可以么?
> > > 
> > > 
> > > 正常来说是可以的，我后面搞了新的EFI，目前用着从14.6直升到15.3都没有问题，99%完成度，十分接近白果了，双系统爽歪歪！
> > > 不过我的是SL7D1，CPU跟SL5D1有差别，我的是6700HQ，但方法都一样（可能选择的机型不同），应该也是通用的。
> > 
> > 
> > 您好，我的也是神舟Z6-SL7D1，目前电池显示不出来，HDMI无法外接屏幕。我装的是黑果小兵的10.15.4，能麻烦您把EFI文件发我一份儿吗？万分感谢。
> 
> 我单独搞一个git，上传到那你可以去看看

大佬请问您的efi能分享一下吗，我的也是z6-sl7d1，自己找的蓝牙有点问题不知道咋修复。。

**Comment by KalonPeng** [comment]
> > > > > 麻烦还要再请教你.😂
> > > > > 这套EFI 装Mojave和Catalina都可以么?
> > > > 
> > > > 
> > > > 正常来说是可以的，我后面搞了新的EFI，目前用着从14.6直升到15.3都没有问题，99%完成度，十分接近白果了，双系统爽歪歪！
> > > > 不过我的是SL7D1，CPU跟SL5D1有差别，我的是6700HQ，但方法都一样（可能选择的机型不同），应该也是通用的。
> > > 
> > > 
> > > 您好，我的也是神舟Z6-SL7D1，目前电池显示不出来，HDMI无法外接屏幕。我装的是黑果小兵的10.15.4，能麻烦您把EFI文件发我一份儿吗？万分感谢。
> > 
> > 
> > 我单独搞一个git，上传到那你可以去看看
> 
> 大佬请问您的efi能分享一下吗，我的也是z6-sl7d1，自己找的蓝牙有点问题不知道咋修复。。

你去GitHub上安装最新的intel wifi驱动就可以了，现在intel的wifi和蓝牙都可以用了
